const SET_LOGUED_ACCOUNT = 'SET_LOGUED_ACCOUNT';

const SET_DESTINATIONS = 'SET_DESTINATIONS';

const SET_SURVEYS = 'SET_SURVEYS';

const SET_TOURS = 'SET_TOURS';

const SET_VOUCHERS = 'SET_VOUCHERS';

const UPDATE_DESTINATION = 'UPDATE_DESTINATION';

const HIDDEN_SURVEYS = 'HIDDEN_SURVEYS';

export { SET_LOGUED_ACCOUNT, SET_DESTINATIONS, UPDATE_DESTINATION, SET_SURVEYS, SET_TOURS, SET_VOUCHERS, HIDDEN_SURVEYS };